-- 追加 DB 検証用スキーマ（Oracle）。Phase 7。
--
-- dev-db/postgresql/migrations/000_init.sql（同梱サンプルの元データ。26テーブル）を
-- Oracle の方言へ移植したもの。スキーマ = 接続ユーザー（docker compose では ERD）。
-- 手動 GUI 検証（docker compose --profile oracle up -d）と内省テスト
-- （OracleIntrospectorTest）で同じファイルを使う。
--
-- 確かめたいこと:
--   - スキーマモードで内省できる
--   - GENERATED ... AS IDENTITY が autoIncrement として取れる
--   - VARCHAR2 / NUMBER / TIMESTAMP / DATE / CLOB の logicalType 正規化
--     （NUMBER(10,2) が decimal、NUMBER(10) が int）
--   - コメントからの論理名の初期値補完（要 remarksReporting=true。テスト側で接続プロパティを付ける）
--   - Oracle は識別子を既定で大文字に畳む。内省結果も大文字になることを確認する
--
-- 移植で変えたところ（PostgreSQL 版との差）:
--   - SERIAL       ... NUMBER GENERATED BY DEFAULT AS IDENTITY
--   - INT          ... NUMBER(10)。桁なしの NUMBER は正規化が割れるため桁を明示する
--   - VARCHAR      ... VARCHAR2
--   - TEXT         ... CLOB
--   - TIMESTAMPTZ  ... TIMESTAMP。WITH TIME ZONE はドライバ固有の DATA_TYPE を返し
--                      正規化の検証から外れるため使わない
--   - comment 列   ... COMMENT は Oracle の予約語のため引用符で囲む。大文字で囲むので
--                      内省結果は他の列と同じ大文字になる
--   - 制約名       ... PostgreSQL が自動で付けるのと同じ形を明示的に付ける
--
-- 文は「1文 = セミコロン終端、文中にセミコロンを含めない」で書く（テストの素朴な分割器が
-- セミコロンで分ける。分割後の各文は JDBC が実行する。JDBC 実行時に末尾のセミコロンは付かない）。
-- PL/SQL ブロックや複数文の一括実行は使わない。DROP は冪等化のためテスト側が事前に流す。
--
-- このコメント自身にもセミコロン記号を書いてはならない。分割器は行コメントを剥がす前に
-- 分割するため、コメント中のセミコロンでも文が切れ、残りの文字列が次の CREATE 文の先頭に
-- 混ざって ORA-00900 になる。

-- -----------------------------
-- ユーザー管理
-- -----------------------------
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

COMMENT ON TABLE users IS 'ユーザー情報';

CREATE TABLE user_profiles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(10) NOT NULL,
    full_name VARCHAR2(255),
    phone_number VARCHAR2(20),
    birth_date DATE,
    CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE user_profiles IS 'ユーザープロファイル';

CREATE TABLE user_addresses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(10) NOT NULL,
    address_line1 VARCHAR2(255) NOT NULL,
    address_line2 VARCHAR2(255),
    city VARCHAR2(100),
    postal_code VARCHAR2(20),
    country VARCHAR2(100),
    CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
    CONSTRAINT user_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE user_addresses IS 'ユーザー住所';

CREATE TABLE user_sessions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(10) NOT NULL,
    session_token VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    expires_at TIMESTAMP,
    CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT user_sessions_session_token_key UNIQUE (session_token),
    CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE user_sessions IS 'ユーザーログインセッション';

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR2(50) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_role_name_key UNIQUE (role_name)
);

COMMENT ON TABLE roles IS 'ロール（権限）';

CREATE TABLE user_roles (
    user_id NUMBER(10) NOT NULL,
    role_id NUMBER(10) NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id)
);

COMMENT ON TABLE user_roles IS 'ユーザーとロールの紐付け';

-- -----------------------------
-- 商品管理
-- -----------------------------
CREATE TABLE product_categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,
    CONSTRAINT product_categories_pkey PRIMARY KEY (id),
    CONSTRAINT product_categories_category_name_key UNIQUE (category_name)
);

COMMENT ON TABLE product_categories IS '商品カテゴリ';

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_id NUMBER(10),
    product_name VARCHAR2(255) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES product_categories(id)
);

COMMENT ON TABLE products IS '商品';

CREATE TABLE product_images (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER(10) NOT NULL,
    image_url VARCHAR2(500) NOT NULL,
    CONSTRAINT product_images_pkey PRIMARY KEY (id),
    CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id)
);

COMMENT ON TABLE product_images IS '商品画像';

CREATE TABLE inventories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER(10) NOT NULL,
    quantity NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT inventories_pkey PRIMARY KEY (id),
    CONSTRAINT inventories_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id)
);

COMMENT ON TABLE inventories IS '在庫管理';

CREATE TABLE product_reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER(10) NOT NULL,
    user_id NUMBER(10) NOT NULL,
    rating NUMBER(10) NOT NULL,
    "COMMENT" CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
    CONSTRAINT product_reviews_rating_check CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE product_reviews IS '商品レビュー';

CREATE TABLE product_tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tag_name VARCHAR2(50) NOT NULL,
    CONSTRAINT product_tags_pkey PRIMARY KEY (id),
    CONSTRAINT product_tags_tag_name_key UNIQUE (tag_name)
);

COMMENT ON TABLE product_tags IS '商品タグ';

CREATE TABLE product_tag_mappings (
    product_id NUMBER(10) NOT NULL,
    tag_id NUMBER(10) NOT NULL,
    CONSTRAINT product_tag_mappings_pkey PRIMARY KEY (product_id, tag_id),
    CONSTRAINT product_tag_mappings_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT product_tag_mappings_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES product_tags(id)
);

COMMENT ON TABLE product_tag_mappings IS '商品とタグのマッピング';

-- -----------------------------
-- 注文管理
-- -----------------------------
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(10) NOT NULL,
    order_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(50) NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE orders IS '注文';

CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER(10) NOT NULL,
    product_id NUMBER(10) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id)
);

COMMENT ON TABLE order_items IS '注文アイテム';

CREATE TABLE shipments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER(10) NOT NULL,
    shipment_date TIMESTAMP,
    carrier VARCHAR2(100),
    CONSTRAINT shipments_pkey PRIMARY KEY (id),
    CONSTRAINT shipments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id)
);

COMMENT ON TABLE shipments IS '出荷情報';

CREATE TABLE order_status_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER(10) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT order_status_logs_pkey PRIMARY KEY (id),
    CONSTRAINT order_status_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id)
);

COMMENT ON TABLE order_status_logs IS '注文ステータス履歴';

CREATE TABLE order_cancellations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER(10) NOT NULL,
    reason CLOB,
    cancelled_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT order_cancellations_pkey PRIMARY KEY (id),
    CONSTRAINT order_cancellations_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id)
);

COMMENT ON TABLE order_cancellations IS '注文キャンセル情報';

-- -----------------------------
-- 決済管理
-- -----------------------------
CREATE TABLE payment_methods (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    method_name VARCHAR2(50) NOT NULL,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
    CONSTRAINT payment_methods_method_name_key UNIQUE (method_name)
);

COMMENT ON TABLE payment_methods IS '支払方法マスタ';

CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER(10) NOT NULL,
    payment_method_id NUMBER(10),
    payment_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    amount NUMBER(10, 2) NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT payments_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id)
);

COMMENT ON TABLE payments IS '支払情報';

CREATE TABLE payment_histories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    payment_id NUMBER(10) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    processed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT payment_histories_pkey PRIMARY KEY (id),
    CONSTRAINT payment_histories_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id)
);

COMMENT ON TABLE payment_histories IS '支払履歴詳細';

CREATE TABLE refunds (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    payment_id NUMBER(10) NOT NULL,
    refund_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    amount NUMBER(10, 2) NOT NULL,
    CONSTRAINT refunds_pkey PRIMARY KEY (id),
    CONSTRAINT refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id)
);

COMMENT ON TABLE refunds IS '返金情報';

-- -----------------------------
-- ポイント管理
-- -----------------------------
CREATE TABLE points (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(10) NOT NULL,
    balance NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT points_pkey PRIMARY KEY (id),
    CONSTRAINT points_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE points IS 'ポイント残高';

CREATE TABLE point_transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(10) NOT NULL,
    points NUMBER(10) NOT NULL,
    transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    description VARCHAR2(255),
    CONSTRAINT point_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT point_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE point_transactions IS 'ポイント履歴';

CREATE TABLE point_campaigns (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    campaign_name VARCHAR2(100) NOT NULL,
    start_date DATE,
    end_date DATE,
    CONSTRAINT point_campaigns_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE point_campaigns IS 'ポイントキャンペーン';

CREATE TABLE point_bonus_rules (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    campaign_id NUMBER(10) NOT NULL,
    bonus_rate NUMBER(5, 2) NOT NULL,
    CONSTRAINT point_bonus_rules_pkey PRIMARY KEY (id),
    CONSTRAINT point_bonus_rules_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES point_campaigns(id)
);

COMMENT ON TABLE point_bonus_rules IS 'ボーナスポイントルール';
