-- 追加 DB 検証用スキーマ（Oracle）。Phase 7。
--
-- H2 の検証（JdbcIntrospectorTest）と同じ形（users / orders / flyway_schema_history）を
-- Oracle の方言で表現する。スキーマ = 接続ユーザー（docker compose では ERD）。
--
-- 確かめたいこと:
--   - スキーマモードで内省できる
--   - GENERATED ... AS IDENTITY が autoIncrement として取れる
--   - VARCHAR2 / NUMBER / TIMESTAMP / CLOB の logicalType 正規化
--     （NUMBER(12,2) が decimal、桁なし NUMBER の扱い）
--   - コメントからの論理名の初期値補完（要 remarksReporting=true。テスト側で接続プロパティを付ける）
--   - Oracle は識別子を既定で大文字に畳む。内省結果も大文字になることを確認する
--
-- 文は「1文 = セミコロン終端、文中にセミコロンを含めない」で書く（テストの素朴な分割器が
-- セミコロンで分ける。分割後の各文は JDBC が実行する。JDBC 実行時に末尾のセミコロンは付かない）。
-- PL/SQL ブロックや複数文の一括実行は使わない。DROP は冪等化のためテスト側が事前に流す。
--
-- このコメント自身にもセミコロン記号を書いてはならない。分割器（DbTestSupport.split）は
-- 行コメントを剥がす前に分割するため、コメント中のセミコロンでも文が切れ、
-- 残りの文字列が次の CREATE 文の先頭に混ざって ORA-00900 になる。

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) NOT NULL,
  org_id NUMBER,
  note CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX users_email_key ON users(email);

CREATE INDEX idx_users_created_at ON users(created_at);

CREATE TABLE orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  total NUMBER(12, 2) NOT NULL,
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE flyway_schema_history (installed_rank NUMBER PRIMARY KEY);

COMMENT ON TABLE users IS 'ユーザーマスタ';

COMMENT ON COLUMN users.email IS 'メールアドレス';
